name = "EduBuddy"
main = "src/index.ts"
compatibility_date = "2023-08-23"
node_compat=true
keep_vars = true

[ai]
binding = "AI"

[vars]
EMBEDDING_MODEL = "@cf/baai/bge-base-en-v1.5"
EMBEDDING_DIMENSION = 768