
const physicsMock = {
    name: "Physics",
    level: "medium",
    description: "Explore the fundamental principles of physics, including motion, energy, forces, quantum mechanics, and field theory.",
    tags: ["science", "physics", "fundamentals"],
    messages: [
        {
          type: "system",
          message: "Welcome! I'm your Physics tutor. Whether you have questions about motion, energy, forces, or quantum mechanics, I'm here to help you explore the wonders of the physical universe.",
          sequenceNo: 1
        }
      ],
      quizzes: [
        {
          // topic: to be set to the Physics course _id when inserted into DB
          questions: [
            {
              question: "Who formulated the three laws of motion?",
              answer: "Isaac Newton",
              options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Niels Bohr"],
              hint: "He also developed the law of universal gravitation."
            },
            {
              question: "What is the unit of force in the International System (SI)?",
              answer: "Newton",
              options: ["Joule", "Pascal", "Newton", "Watt"],
              hint: "It's named after a famous physicist."
            },
            {
              question: "Which fundamental force is responsible for holding the nucleus together?",
              answer: "Strong nuclear force",
              options: ["Electromagnetic force", "Strong nuclear force", "Weak nuclear force", "Gravitational force"],
              hint: "It's the strongest force but acts over a very short range."
            }
          ],
          scores: [],
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days from now
        }
      ],
      assignments: [
        {
          // course: to be set to the Physics course _id when inserted into DB
          question: "Describe the difference between kinetic energy and potential energy. Provide real-world examples of each and explain the principle of conservation of energy.",
          dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days from now
          submissions: [],
          status: "Pending"
        }
      ],
    resources: [
        {
          videoLink: "https://www.youtube.com/embed/ZAqIoDhornk",
          transcript: `
      Hi! You’re on a rock. Floating in space. Surrounded by more rocks. And gas. And a bunch of nothing, mainly. Oh hey, look at that, the rocks are going around the gas. Hold on, what the heck is going on here? To understand, let’s look a little bit of Physics. Wait, did I say a little bit? To find out what kind of magic this is, we’ll have to go back in time. Okay, not that far. Stop! Yeah. That’s perfect. This is gravity guy. But most people call him “Isaac Newton”. One important thing he said is that Force equals mass times acceleration. Now what do all these words even mean? Force is just a push or pull on something, in a certain direction. Mass tells you how much of something there is, and it’s also a measure of inertia, but we’ll get to that later, and acceleration is the derivative of velocity with respect to time, but that’s too many big words for my taste, so let’s just say it’s how fast velocity is changing. The key takeaway is that if you apply a Force to a fixed mass, you get a predictable amount of acceleration. If you know all the forces acting on a basketball mid-air, you can predict with 100% certainty if the ball will go in the hoop or your neighbor’s windshield.
      “Whoa, did an apple just fall on my head?” Yes Newton, it did. “That must have happened for a reason,” said Newton, as he discovered that two masses attract one another, making the apple fall. Yes, even you, no matter how ugly you think you are, attract pretty much the whole universe, at least a little bit. “Hey, can you put that on paper?” “Yup,” said Newton, who gave us the Law of Universal Gravitation. In other words, how much two bodies pull on each other, given their mass and distance, times a constant. Bigger mass? Bigger Pull. Bigger distance? Smaller pull. Actually, a lot smaller pull. You see, as the distance increases, the Force gets smaller by the square. That, my friends, is the Inverse-Square Law. Gravity is also the reason why the planets in our solar system orbit the sun. They got their initial velocity when the solar system formed out of spinning gas, and since there’s nothing in space to stop them from moving, they’ll keep moving. Hey, that’s Newton’s first Law. The sun is so massive, that the force of gravity keeps pulling the planets towards the sun, but the planets are fast enough to essentially fall towards the sun but miss it, and this goes on forever, creating a round orbit. Actually, that’s kind of a lie. Most orbits are not perfectly round but more egg-shaped and Pluto’s orbit is just…a complete mess. But you get the idea. In this case, the gravity is what we call a centripetal force.
      One thing many people confuse is mass and weight, and no, they are not the same. Mass tells you how much of this blob there is, and Weight is the force of Gravity the blob would feel. To make things clear, your mass would be the same on the earth and on the moon, but the “weight” you would perceive is different, because the moon has a weaker gravitational pull, meaning, a weaker force acting on your mass. So really, you’re not overweight, you’re just on the wrong planet.
      Aight, enough about Newton, let’s break some stuff. If you ever dropped your phone, it might look like this: What the hell ground, why’d you do that? The answer is Energy. You know, the thing kids have after eating gummy bears. Energy has the unit Joule. And it’s not like Force, it doesn’t have a direction, it’s just a number, that’s kind of chilling there, as a property of a thing. You see, there’s two main kinds of energy: Kinetic energy, and potential energy. In plain English, energy of movement, and stored energy due to some circumstance. For example, when you held your phone, it stored gravitational potential energy, due to being held above the ground, at a certain height. Once you dropped it, the potential energy was converted into kinetic energy, as the phone fell. Then it smashed into the ground, and the phone absorbed some of the energy making the screen go boom.
      Work is defined as Force applied over distance. For example: If you lift an apple by 1 meter, you would have done about 1 Joule of work. This happened by converting chemical energy stored in your body to gravitational potential energy stored in the apple. As you may have noticed, Energy and Work have the same unit “Joule”. So they must be the same thing? Uhhh, No. Energy is the total amount of work that a thing could possibly do. Work is just the stuff that actually happened and required energy. You know, force applied over a distance, which most often implies converting energy from one form to another.
      If you try to lift a weight that’s too heavy for you, you’d feel like that took a bunch of work, right? Well, yes, but your feelings are invalid in the face of Physics! Mathematically, no work has been done! Because, work is a force applied over a distance. And since you didn’t move the weight at all, no distance means no work. The key thing to remember about energy is that it cannot be created or destroyed, only converted. Aka, the conservation of energy. Okay, but a car that’s moving has kinetic energy. When the car stops, assuming the car doesn’t smash into a wall, where does that energy go? When you apply the brakes, there’s friction between the brakes and the wheels, causing the car to slow down, and creating heat as a byproduct. That heat is then dissipated to the surrounding air. And that makes the molecules in the air move faster. And things that move have kinetic energy. So ultimately, the kinetic energy is transferred from the car to the air. With this knowledge, we can define that Temperature is just the average kinetic energy of atoms in a system. You see, all atoms, not just molecules in the air, wiggle. Like this. The faster they move, the hotter things get. That is temperature.
      All that talk about hot stuff, I think it’s time we talk about Thermodynamics. It tells us that jumping in lava is probably a bad idea, but more importantly, the absolute mess that is entropy. Literally, it tells you how much disorder there is in a system, indicating the number of possible states a system can be in. For example, get an ice cube, no not that one, yes that’s perfect, and put it in the sun. The sun will obliterate the ice cube and turn it into water. Looking at the structure of ice and water, we can see that ice is more neatly organized than water, which just kind of goes all over the place. Also, the water could look like this, or this, or even this, but the ice will always look a little something like this. In total, the system went from low entropy to high entropy, meaning more disorder and more possible microstates. This trend applies to everything. The whole universe is on an unstoppable path to higher entropy. It’s also the reason why time seems to go only forwards, or at least, that’s what we believe at this point. Practically, entropy tells us that some forms of energy are more useful for doing work than others. Burn some gasoline, and your car will move, spitting out heat and gas. That heat and gas is pretty much gasoline, just in the form of higher entropy. And as you can imagine, this stuff won’t really make your car move, and the gas won’t spontaneously turn back into liquid gasoline. Meaning, the form of gasoline with lower entropy is more useful for doing work.
      Okay, but if you put some water in the freezer, will it not decrease in entropy? Yes, BUT the fridge is not an isolated system and will heat up the room more than it will cool down the water, increasing the total entropy.
      Wanna see some magic? Woah, what just happened? Some electrons apparently moved through some wires and let there be light. What is going on here? Objects have a fancy something called a charge. It can be positive or negative. Or, if you have the same amount of both, an object is neutral. Electrons have a single negative charge. The flow of electrons is called electric current. To describe it, we use three parameters: Current, Voltage, and Resistance. Current is the amount of electrons passing through a wire in a given amount of time, Voltage is what pushes the electrons to move, but simply put, it’s a difference in electric potential, so you can imagine it as a slope that goes from high potential to low potential, where the flow of current goes downhill, and resistance is pretty self explanatory. This is Coulomb’s Law. Wait a minute, this is just Newton’s Law of Gravitation in disguise! This tells us that electric charges attract each other in a similar way masses do. Opposites want to cuddle, while like charges literally couldn’t think of a more disgusting thing than to be with one another. These four equations explain pretty much all of electromagnetism. But don’t be scared just because they look scary! I mean, yeah, they do, but it’s simpler than it seems at first.
      The first one states that if there is an electric charge, there will be an Electric field, or this big E, emerging from it. Add another and you have an electrostatic field. These lines tell us in which direction a charged particle would feel a force at any given point. The second one tells us the same for magnetic fields, AND, even though electric charges are cool and can be alone, magnetic poles are not. They’re very lonely. There will always be a north pole together with a south pole, and a single pole can never be alone. Okay now here’s where things get kind of freaky. You know how electric charges only act on other charges, and magnets only affect other magnets? Well that’s only true if they’re not moving. The third and fourth maxwell equations tell us that a moving magnet creates an electric field, and a moving charge or electric field creates a magnetic field. One consequence of this is that current can seemingly come “out of nowhere” by moving a magnet next to a conductor. The moving magnet creates an electric field, which makes the electrons inside the conductors go crazy. That is called induction. It’s the reason why your phone charges when you put it on the charging pad, even though it is not directly connected to a cable. In other words, electric and magnetic fields are so tightly linked that they are the two parts of the same bigger thing. Let’s say we have a charge. Since it doesn’t move, it has a static electric field. If we accelerate the charge, there will be a magnetic field around it. That magnetic field interacts with the electric field, which again changes the magnetic field, and this is a sort of chain reaction that makes the electromagnetic field radiate outwards into space as an electromagnetic wave. Depending on the frequency, the human eye can actually see this, it’s called light, but most of the spectrum is invisible to the human eye and is used for things such as Bluetooth, wireless charging and confusing human apes into thinking magic is real.
      Hey, can we go back to the water and look at those molecules? Yeah, those, what are they made of? The molecules are made of Atoms. Atoms are made of a core and some electrons. The core is made of protons and neutrons, both of which are made of quarks. They’re strange yet charming, from up top down to the bottom. Oh yeah there’s some more stuff, like for example the overweight brothers of the electron. All of this together makes up the standard model, which we believe to be the smallest things in the universe. At least that’s the excuse we have for not knowing what quarks are made of. Fun Fact! Depending on the number of protons in the core, you get different elements. Depending on the number of Neutrons in the core, you get different Isotopes of the same element. Most of which are a little overweight and very unstable. So they fall apart, into smaller atoms. That releases ionizing radiation. Not so fun fact: That stuff will kill you. Do not play with radioactive atoms. If you have a large group of atoms, you can predict when half of those will have fallen apart. That’s the halflife. Depending on how unstable an isotope is, it will survive a certain amount of time. Some don’t want to live, some really don’t want to live, but some will live far longer than you probably will.
      Oh yeah, did I mention that light is like the fastest thing in the universe? To be exact, 299,792,458 meters per second in a vacuum. “That is pretty fast” said everyone. Also, “Light is a wave” said everyone. Why? If you shoot it through two teeny tiny slits it creates a fancy pattern due to interference, which is just a wave thing. You see, when two waves cross, they can add up, or cancel each other out. These gaps, are the spots where they cancel each other out, so in this case, light behaves like a wave. “Nah, screw that, everything you know is wrong” said Albert Einstein, probably smoking crack, after hearing about the photoelectric effect and discovering that light comes in tiny packets called photons. I sure hope that doesn’t unravel a whole new area of physics, haha. “Anyway,” he said, as he continued to casually drop an absolute bomb on the entire field of physics with his theory of relativity: He assumed the speed of light is constant because it arises from two other constants. He also assumed the laws of physics are the same for everyone, regardless if moving or at rest. Now think about it: If two people turn on a flashlight, but one person is standing still, while the other person is on a moving train, wouldn’t the person standing still see the other person’s light as going faster than the speed of light? The reality is: NO! It would be the same as their own flashlight. That’s impossible, except if time passes slower for that person from the perspective of this person. In other words, if the speed of light is constant, time must be relative. Also, gravity is not actually a Force, sorry Newton, but rather a consequence of masses bending spacetime. Einstein thought that the universe is a mesh of space and time, and anything with a mass bends this fabric. Also, all objects move freely on a straight line when moving through space. Gravitation is simply the result of objects following these bent lines, which appear straight to them. If you have a hard time understanding this, you can imagine two people on earth, walking in parallel, straight lines. On a short distance, the straight lines will never meet. Now imagine one standing on the east coast, and one the west coast of the US. If they both walk north, eventually, they will meet at the north pole. Because of the curvature of the earth, they ended up at the same point even though they both walked “straight” relative to themselves. “Oh yeah by the way Energy and mass are kind of the same thing,” he added, which explains why atom bombs are so frickin powerful. According to this formula, even just tiny atoms can release a humongous amount of energy by giving up just a fraction of their mass during fission.
      What is Fission? It’s the same thing Oppenheimer used to make this thing go boom. You see, there’s two main ways to gain energy from changing nuclei: Fission and Fusion. Fission aims to split the nucleus of an atom into two or more smaller nuclei, which is most often achieved by blasting the core with neutrons. Fusion is the opposite, where you combine two smaller nuclei to get one bigger one. The energy came from something we call a “mass defect” where the resulting nucleus is lighter than the starting nuclei. This “missing” mass is what was converted to energy during Fusion. Fission and Fusion are cool, but you have got to be careful or you might just blow up the planet. That totally didn’t almost happen before… multiple times.
      Hey remember when Einstein said light is a particle? He accidentally discovered a whole new field of physics which he thought is just a giant hoax: Quantum Mechanics. This stuff is crazy. Another German guy called Max Planck said “yes, Einstein, you’re right. Light does come in tiny packets. Actually, all energy comes in tiny packets”. He is the daddy of Quantum Mechanics. Wanna know where an electron is inside an atom? It’s here! And there! And everywhere, at the same time, actually! That’s a superposition. It’s not in one state, it’s in multiple states at once - at least until you measure it. Then it chooses one cozy spot to be in. Schrödinger gave us an equation that gives you a probabilistic model of where you can find it if you were to measure. You can imagine this as a cloud, and the denser it is, the more likely it is for an electron to be there. But still, where exactly it will end up once you measure it, is random.
      Speaking of observing particles, they’re also super sensitive about their private data. Look at these two images of a flying ball: in one, you can clearly see where the ball is, but not in which direction it’s moving, and in the other you can see where it’s moving and approximately how fast, but not where exactly it is at the moment. That is essentially Heisenberg’s uncertainty principle: You can never know both the exact position and the exact speed of a quantum particle at the same time. Okay, let’s recap, a small thing can be a particle and a wave at the same time, and when we try to look at them, weird stuff happens. But you know what, it gets even weirder. Think back to the double slit experiment: We know that a light beam acts as a bunch of waves and we get interference. But here’s the weird thing: Even if you send individual photons, after sending enough of them and detecting where they end up, you get interference. Like, how can that be? What did a single particle interfere with? Well, we think it interfered with itself, because it acted as a wave and went through both slits at the same time. That’s a superposition. “Okay, well let’s just measure which slit it goes through”. Uh, yeah, that’s not going to happen. Once you start measuring which slit the photon goes through, it stops acting like a wave and the interference pattern disappears, as every particle chooses just one of the slits to go through. Sounds kinda suspicious to me.
      Anyways, all this knowledge is going to cost you one subscribe and a thumbs up, thank you very much, and you can decide if maybe you’d want to tip with a comment, perhaps?
          `
        },
        {
          videoLink: "https://www.youtube.com/embed/n7cOlBxtKSo",
          transcript: `
      [Music] Welcome back to Science Clique. Today: String Theory. Our universe contains matter which, when we look closer, is made up of particles. There are different types of particles: electrons, quarks, or neutrinos. Particles move in the universe and can interact by exchanging other particles. The electromagnetic force, for example, is mediated by the exchange of photons. All these different particles are accounted for in what we call the standard model. It is currently our most precise mathematical description of the quantum world. It contains two main categories of particles: fermions, which mostly constitute matter, and bosons, which mostly describe interactions.
      At first glance, one might think that this is the ultimate theory, that the standard model describes everything. But unfortunately, there is another interaction that this model doesn't account for: gravity. On a large scale, we know that gravity is described by general relativity. Objects curve space-time, thus attracting other objects. As with other types of interactions, we expect that the curvature of space-time is made up of small particles at the quantum scale—quanta of space-time curvature called gravitons.
      [Music] But when we try to include the graviton in the standard model, the calculations give absurd results with infinite values that cannot be removed. We cannot describe gravity on the quantum scale. It is to solve this problem that physicists have been looking for new theories for more than half a century. In this video, we are going to build together one of the most promising approaches: string theory.
      [Music] The basic idea is quite simple. In the standard model, particles are described as small dimensionless points. We admit that these points do not all have the same properties to account for the fact that there are different types of particles. In string theory, we will assume that this is only an approximation, and that if we zoom in on the particles, they are all made up of a small string, sometimes open and sometimes closed. These little strings have tension like tiny rubber bands, and they can vibrate.
      A guitar string can vibrate in different modes—harmonics. Likewise, our little strings can vibrate in different ways: one ripple, two ripples, three ripples, and so on. The different vibrating modes behave on our scale like particles of different types. When we perform the calculations, we discover in particular that some strings behave like photons, and better still, some like gravitons.
      [Music] Starting from the sole principle that particles are tiny strings with tension, we already explain why there are different types of particles, and we naturally predict the existence of the graviton, thus describing gravity at the quantum scale.
      We now want to understand how these strings evolve through the universe. For that, we will use the same principles as our current models. Imagine that we throw an electron at a target. The electron propagates like a wave and when it reaches the target, we can't know for sure where it will materialize. At the quantum scale, the same experiment can give different results. We can only predict the probability of observing such or such results, and the goal of physics at this scale is to determine these probabilities.
      [Music] The mathematical approach to determine the probability of observing a particular result is to consider all possible scenarios that lead to it at the same time. We sum all trajectories but also all possible interactions. For example, an electron can emit a photon then reabsorb it, or two photons, or even three. In all the scenarios that we consider, we manually decide to allow such or such types of interactions to reproduce what we observe in reality. And by summing all these scenarios, we obtain the desired probability.
      In string theory, the approach is the same; however, the particles are no longer points. A point traces a trajectory over time, but a string traces a surface. To describe the evolution of a string in a probabilistic way as in quantum physics, we will consider all possible geometries that the string can trace over time. It can follow a specific trajectory, vibrate in a certain way, but also duplicate itself, which amounts to emitting a particle, or recombine, which amounts to reabsorbing the particle, forming a geometry with a hole. By summing up all possible geometries, string theory automatically includes interactions—there is no need to add them manually.
      Incidentally, interactions in the standard model were local: the emission of a photon was instantaneous, for example. In string theory, interactions are now continuous. Particles are no longer emitted instantaneously but gradually. This gets rid of the infinities that we obtained when we tried to include the graviton in the standard model. In this way, string theory not only predicts the existence of the graviton, but it also allows us to calculate how it interacts with other particles and therefore to describe quantum gravity.
      [Music] So far, the theory looks very promising. It explains why there are different types of particles, it predicts that they can interact, and it includes a quantum description of gravity. Unfortunately, at this stage, the model exhibits three problems. First problem: all the strings behave like bosons, such as photons or gravitons. In our world, there is another category of particles—fermions, such as electrons—but so far our model does not predict such particles. Second problem: one of the particles predicted by the theory is what we call a tachyon; its mass appears to be an imaginary number, the square root of a negative number. It is a mathematical problem that we must get rid of. Finally, the third problem: our space-time has four dimensions—three dimensions of space and one of time—but this theory only seems to work in a universe with 26 dimensions.
      At this stage, string theory seems very far from describing our universe. To solve these problems, we'll have to push the theory a little further to include fermions in our model. The idea is to add spinners on the strings—they are the mathematical ingredient that already described fermions in the standard model. By simply adding spinners to the strings, we solve two problems: the model now predicts the existence of fermions, and it no longer predicts the tachyon, the particle that was problematic. This more complete theory is called superstring theory. In fact, now that we added spinners, our theory exhibits a fundamental symmetry between fermions and bosons. In a way, it predicts that there would be as many bosons as there are fermions. This is called supersymmetry.
      What about the third problem? Before we included supersymmetry, the mathematics required a 26-dimensional universe. Now superstring theory requires a universe with 10 dimensions.
      [Music] Unfortunately, this third problem is not resolved. The theory does not seem to fit our universe, which only has four dimensions. Yet so far, the model was very promising. Should we abandon it for all that? If they exist, where would these six missing dimensions be? One possibility is that our universe could just be a three-dimensional slice of a larger nine-dimensional universe.
      [Music] Another possibility could be that the six dimensions that we do not observe are curled up on themselves. To understand, let's imagine an ant walking on a straw. The straw has two dimensions: the ant can walk back and forth and left to right around the circumference of the straw. If we zoom out enough, we only notice one of the two dimensions. The second one that curls around the straw is very small and cannot be seen on this scale. In string theory, we can assume a similar phenomenon: our universe would have nine dimensions of space, but six of them would be very small dimensions curled up on themselves so that we do not see them on our scale.
      This hypothesis may seem a little far-fetched. Is it reasonable to assume the existence of dimensions that we do not observe? But it turns out that the existence of additional dimensions is a very interesting question that suggests phenomena that we might observe. For example, we could imagine a massless particle that moves at the speed of light but partially inside a compact dimension.
      [Music] From our point of view, we do not see this dimension, and therefore the particles seem slower to us. We only observe part of its full motion. It seems slowed down as if it had a mass. The idea of additional compactified dimensions thus suggests a fairly simple mechanism through which some particles might exhibit a large mass. However, it would currently require too much energy for us to create them in our particle accelerators and confirm or not their existence.
      The presence of these additional dimensions also allows a much more varied range of vibrational modes and therefore a greater diversity of potential types of particles. In addition, there are a multitude of different ways to curl up six dimensions, and each possibility will predict a different universe where the strings can adopt different vibrational modes and therefore behave like different particles.
      By carefully choosing the way in which these six dimensions are compactified, we can adjust our description so that it predicts the same particles as those we observe in our world. That said, among the myriad of possibilities, it is not yet clear why our universe would contain the particles of the standard model rather than some other possibility. According to some still speculative hypotheses, the geometry of the universe might even have varied over time, transitioning from one compactification to another, and the laws of physics could thus have changed during the first instance of our universe.
      To conclude, string theory remains to this day a speculative model very difficult to test experimentally, since the strings would be incredibly tiny, and which is only one approach among many others in the quest of finding the ultimate theory. However, it is still one of the most promising models whose insights have far exceeded its original goals. Strings allow us to describe gravity on the quantum scale and open doors to the study of black holes. They help develop several fields of mathematics and get a better understanding of the standard model itself. String theory even offers hypothetical candidates for particles such as axions to potentially explain dark matter. That said, there is still a lot of research to do, in particular the aspects of string theory that are best understood rely heavily on supersymmetry, which tends to predict the existence of additional particles which we don't seem to observe yet. There are some compactifications that would explain that we don't observe supersymmetry; however, these are still very rare and not well understood.
      Finally, to venture even further, there actually exist five different versions of superstring theory describing different types of universes. We can show mathematically that these five theories are in reality approximations of a single, more complete model describing a universe with eleven dimensions: M-theory.
      [Music]
          `
        },
        {
          videoLink: "https://www.youtube.com/embed/MmG2ah5Df4g",
          transcript: `
      [Music] Welcome back to Science Clique. Today: Quantum Field Theory. Unlike a marble which has a definite position, at the microscopic scale a particle does not really have a position. Its presence is distributed throughout space with more or less probability. This description of particles as waves of probability is called quantum mechanics. Quantum mechanics allows us to describe the evolution of a particle over time. However, this description, as effective as it is, fails to take into account two considerations.
      Firstly, quantum mechanics cannot describe situations where the number of particles varies over time. However, in nature, we often observe that particles can appear or disappear, like when a photon gets absorbed by an electron in an atom. Secondly, quantum mechanics treats each particle independently. However, within a family of particles such as electrons, all exhibit the same properties and behaviors. How is it that an electron coming from the far reaches of the cosmos has exactly the same mass or charge as an electron in an apple?
      To answer this question, we will have to build a new mathematical framework—a more general description that reconciles quantum mechanics with special relativity. We will construct the most successful framework available for describing the microscopic world. In this video, we build together quantum field theory.
      To begin with, let's start with an empty universe. Relativity teaches us that the fabric of the universe is space-time. To simplify, we will represent only two dimensions of space as well as the dimension of time. We now want to fill our universe with content—matter. We saw previously that all particles of the same type, for example all electrons, appear perfectly identical, as if they were only local manifestations of a single underlying object which would fill the whole universe: a field. To add content to our universe, we will therefore start by adding a field.
      [Music] In mathematics, a field is like a fluid which fills all space-time, each point of which is populated by a mathematical object. It can be a field of numbers, vectors, or other more exotic objects. That said, special relativity imposes some restrictions. It forces us to respect certain symmetries which correspond to the geometry of space-time: symmetries of translation, rotation, or changing frame of reference. [Music] These symmetries are only respected by certain mathematical objects, and we can classify them with a parameter: spin.
      The simplest objects that we can use are numbers. We give them spin zero because when we rotate space around a number, it does not vary. Vectors, on the other hand, indicate a direction in space—their appearance depends on the orientation in which they are observed. We assign them spin one because when we rotate space by a full turn, a vector also describes a full turn. Finally, relativity also allows other more exotic objects, and in particular spinners which have spin one half. You have to make two turns around a spinner for it to come back to its initial state.
      [Music] All these mathematical objects seem very abstract, and some are difficult to understand, but technically they all obey the symmetries of relativity and are therefore potential candidates with which we could fill our universe.
      [Music] In addition to imposing the types of objects that are allowed, space-time symmetries also set restrictions on the way objects behave inside the field. Each symmetry forces the field to respect the conservation of certain quantities over time. To obey relativity, our field must respect the conservation of energy, momentum, angular momentum, and velocity of the center of mass. Moreover, the mathematical objects themselves can contain symmetries of their own. If we decide to form a field with complex numbers, for example, they exhibit an internal symmetry which implies the conservation of another quantity over time related to the very nature of complex numbers: the electric charge.
      [Music] At this stage, we have a space time which we have filled with a field which satisfies all the restrictions imposed by special relativity. But our goal is to describe the microscopic world, so it's time to turn our field into a quantum field.
      [Music] In quantum mechanics, to transform a classical object into a quantum object, we allowed it to adopt several positions at the same time with more or less probability. Similarly, to transform a classical field into a quantum field, we allow it to adopt several configurations—multiple ways it can evolve with more or less importance. Over time, our field evolves as a superposition of all possible scenarios. Transitioning from a classical field to a quantum field results in a very interesting property. Just like an electron in an atom has well-defined energy levels, a quantum field also has energy levels. It can only contain an integer number of disturbances—quanta of energy that can appear or disappear. These are particles. Much like a wave on the surface of water, a particle is simply a disturbance which propagates within the field.
      [Music] A quantum field is also agitated by fluctuations which keep popping in and out of existence—these are called virtual particles. These virtual particles exist only very briefly, so that it is strictly impossible to observe them.
      [Music] Step by step, our model universe is getting closer to reality. We now describe a space-time filled with a quantum field inside which move disturbances (particles) in a soup of fluctuations (virtual particles). In our universe, several fields coexist and constitute different families of particles. Some are vector fields (spin 1) and the particles they contain are photons, Z and W bosons, and gluons. Others are fields of spinners (spin one half); they are the fermions that make up matter: quarks, electrons, muons, tau particles, and neutrinos. Finally, there is a field of spin zero: the Higgs field. Among all these fields, most have internal symmetries, which provide them with quantities that are conserved over time—charges which distinguish their particles between several versions.
      We saw previously that fields formed with complex numbers have a symmetry which gives them their electric charge. This symmetry allows us to distinguish two versions of the particles: one with positive charge, the other with negative charge. This is anti-matter in a way. The anti-particle is the complex conjugate of the ordinary particle. Other fields also have more exotic symmetries. The quark fields, for example, exhibit a symmetry which assigns them another charge—the colour charge—which must also be conserved over time and that allows us to separate quarks into three versions: red, green, and blue. The set of all these fields that make up the content of our universe is the standard model of particle physics. To this day, this is the most successful description of our universe on the microscopic scale.
      [Music] Our model universe now contains the same particles as our real universe. However, it still isn't realistic. Indeed, the symmetries of space time force all particles to move in straight lines forever, independently one from the other. To finally complete our model, all we have to do is add one more fundamental ingredient: we need to allow these fields to interact with each other.
      [Music] To understand, let's focus on one of the simplest interactions: between the photon field and the electron field. We will allow an electron to emit or absorb a virtual photon, and vice versa. Allowing only this simple interaction will have drastic consequences. For instance, in the following situation, we start with two electrons motionless. Over time, the two electrons progress towards the future. At first, one might think that the two electrons remain motionless indefinitely, but that would be forgetting that our electrons are constantly moving through the photon field with which we allowed them to interact.
      [Music] We saw that a quantum field realizes all possible evolutions at the same time. In a way, each evolution describes a scenario, and in some of these scenarios the electrons will interact with the photon field. In this scenario, for example, the electron emits a virtual photon at a certain instant which carries away part of its momentum, and the virtual photon is absorbed a little later by the other electron. In this other scenario, the electrons exchange this time two photons, or again in this third, more complex scenario, the electron emits a virtual photon which is converted into a pair of virtual electron and positron that annihilate together into a virtual photon which finally ends up absorbed by the second electron.
      By exchanging part of their momentum carried by virtual particles, the two electrons will in some scenarios get closer, and in others get further apart.
      Now consider the following analogy: on a guitar, a string can vibrate with different frequencies, each of which corresponds to a pure sound. But when we pluck the string, it starts to vibrate in a superposition of all these frequencies with more or less amplitude, and the synthesis of all these pure sounds together with different amplitudes is what makes the total sound produced by the string.
      Similarly, a quantum field evolves according to every possible scenario with more or less amplitude, and it is the synthesis of all these scenarios together that describe the real evolution of the physical system. In particular, in our example, when we add up all these possibilities, we observe that overall our two electrons are more and more deflected—they feel a force repelling them because of the exchanges of virtual photons. This is the electromagnetic force. And if instead we had started with an electron and a positron of opposite charge, the amplitudes of the different scenarios would have been different, resulting this time in an overall attraction force.
      [Music] By allowing particles to interact and exchange momentum, quantum field theory explains how forces arise from simple symmetries—the symmetries of the fields which make up our universe.
      [Music] To conclude, quantum field theory is a mathematical recipe for building a model universe. We start with an empty space-time, which we fill with quantum fields that satisfy the symmetries of special relativity. Quantum field theory thus makes it possible to construct a quantum description of our universe which satisfies the constraints imposed by relativity. By allowing fields to interact with each other, this theory makes it possible to predict with astounding precision the phenomena that govern our universe. According to quantum field theory, the evolution of our universe is described as the synthesis of all possible scenarios at the microscopic scale.
      That being said, this description remains incomplete, as even though it satisfies special relativity, quantum field theory cannot be unified with general relativity, which describes gravitation by the curvature of space-time. Some results of the theory can already be calculated in curved space times, such as the prediction that black holes evaporate over time. However, scientists are still looking for a unified theory that would explain microscopically why space-time gets curved and would reconcile the infinitely large with the infinitely small—gravity with quantum—a theory of everything.
      [Music]
          `
        }
      ]
  };
  
  module.exports = physicsMock;
  